StartupEvents.registry('item', event => {
      event.create('neutronium_plate')
      .displayName('中子素板')
      .texture('kubejs:item/avaritia/neutronium_plate') 
      .rarity('common')
      .maxStackSize(64)

      event.create('dense_neutronium_plate')
      .displayName('致密中子素板')
      .texture('kubejs:item/avaritia/dense_neutronium_plate') 
      .rarity('common')
      .maxStackSize(64)

      event.create('double_neutronium_plate')
      .displayName('双重中子素板')
      .texture('kubejs:item/avaritia/double_neutronium_plate') 
      .rarity('common')
      .maxStackSize(64)

      event.create('curved_neutronium_plate')
      .displayName('弯曲中子素板')
      .texture('kubejs:item/avaritia/curved_neutronium_plate') 
      .rarity('common')
      .maxStackSize(64)

      event.create('small_neutronium_gear')
      .displayName('小型中子素齿轮')
      .texture('kubejs:item/avaritia/small_neutronium_gear') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_gear')
      .displayName('中子素齿轮')
      .texture('kubejs:item/avaritia/neutronium_gear') 
      .rarity('common')
      .maxStackSize(64)

      event.create('fine_neutronium_wire')
      .displayName('细中子素齿轮')
      .texture('kubejs:item/avaritia/fine_neutronium_wire') 
      .rarity('common')
      .maxStackSize(64)

      event.create('long_neutronium_rod')
      .displayName('中子素长杆')
      .texture('kubejs:item/avaritia/long_neutronium_rod') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_bolt')
      .displayName('中子素螺栓')
      .texture('kubejs:item/avaritia/neutronium_bolt') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_foil')
      .displayName('中子素箔')
      .texture('kubejs:item/avaritia/neutronium_foil') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_ring')
      .displayName('中子素环')
      .texture('kubejs:item/avaritia/neutronium_ring') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_rod')
      .displayName('中子素杆')
      .texture('kubejs:item/avaritia/neutronium_rod') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_screw')
      .displayName('中子素螺丝')
      .texture('kubejs:item/avaritia/neutronium_screw') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_rotor')
      .displayName('中子素转子')
      .texture('kubejs:item/avaritia/neutronium_rotor') 
      .rarity('common')
      .maxStackSize(64)

      event.create('neutronium_dust')
      .displayName('中子素粉')
      .texture('kubejs:item/avaritia/neutronium_dust') 
      .rarity('common')
      .maxStackSize(64)
 });